pipeline {
    agent any
    
    tools {
        jdk 'jdk11'
        maven 'maven3'
    }
    
    // environment {
        // SCANNER_HOME = tool 'sonar-scanner'
    // }
    
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/jaiswaladi246/Shopping-Cart.git'
            }
        }
        
        stage('Compile') {
            steps {
                sh "mvn clean compile"
            }
        }
        
        // stage('Sonarqube Analysis') {
            // steps {
                // sh '''
                    // $SCANNER_HOME/bin/sonar-scanner \
                    // -Dsonar.url=http://13.233.102.184:9000/ \
                    // -Dsonar.login=squ_815b4e28b618be7ab62693da256718391e4046d3 \
                    // -Dsonar.projectName=Shopping-Cart \
                    // -Dsonar.java.binaries=. \
                    // -Dsonar.projectKey=Shopping-Cart
                // '''
            // }
        // }
        
        stage('Build') {
            steps {
                sh "mvn clean package -DskipTests=true"
            }
        }
        
        // stage('OWASP Dependency Check') {
            // steps {
                // // dependencyCheck additionalArguments: '--scan target/', odcInstallation: 'owasp'
                // dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            // }
        // }
                
        stage('Build Docker Image') {
            steps {
                script {
                    
                    withDockerRegistry(credentialsId: 'abf88e57-9afb-4fc6-a683-ec7100100def', toolName: 'docker') {
                        sh "docker build -t shopping-cart -f docker/Dockerfile ."
                        sh "docker tag shopping-cart 90041/shopping-cart:latest"
                    }
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'abf88e57-9afb-4fc6-a683-ec7100100def', toolName: 'docker') {
                        sh "docker push 90041/shopping-cart:latest"
                    }
                }
            }
        }
        
        stage('Deploy To Docker Container') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'abf88e57-9afb-4fc6-a683-ec7100100def', toolName: 'docker') {
                        sh "docker run -d --name shopping -p 8070:8070 90041/shopping-cart:latest"
                    }
                }
            }
        }
    }
}